apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit737-week10p-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit737-week10p
  template:
    metadata:
      labels:
        app: sit737-week10p
    spec:
      containers:
      - name: sit737-week10p-container
        image: gcr.io/sit737-week10p/sit737-task-10p:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3010